import { NextRequest, NextResponse } from 'next/server';

export async function GET(req: NextRequest) {
  const formDefinition = {
    id: 'default_global_form_def',
    name: 'Formulaire d’inscription Standard (Global)',
    schoolId: null,
    academicYearId: null,
    version: 1,
    status: 'PUBLISHED',
    documentStep: {
      isVisible: true,
      labelFr: 'Étape 4 — Documents',
      labelAr: 'المرحلة 4 — الوثائق',
      descriptionFr: 'Joignez les pièces justificatives requises. Vous pouvez aussi les envoyer ultérieurement par email ou en personne.',
      descriptionAr: 'يرجى إرفاق الوثائق المطلوبة.',
      displayOrder: 4,
    },
    sections: [
      {
        id: 'sec_establishment',
        key: 'establishment_level',
        labelFr: 'Établissement & Niveau',
        labelAr: 'المؤسسة والمستوى',
        displayOrder: 1,
        isVisible: true,
        fields: [
          {
            id: 'fld_school',
            fieldKey: 'school_id',
            fieldType: 'SELECT',
            labelFr: 'Établissement',
            labelAr: 'المؤسسة',
            placeholderFr: 'Sélectionnez un établissement',
            placeholderAr: 'اختر مؤسسة',
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 1,
            width: 'full',
          },
          {
            id: 'fld_level',
            fieldKey: 'level_id',
            fieldType: 'SELECT',
            labelFr: 'Niveau scolaire demandé',
            labelAr: 'المستوى الدراسي المطلوب',
            placeholderFr: 'Sélectionnez le niveau',
            placeholderAr: 'اختر المستوى',
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 2,
            width: 'full',
          },
        ],
      },
      {
        id: 'sec_student',
        key: 'student_info',
        labelFr: 'Informations Élève',
        labelAr: 'معلومات التلميذ',
        displayOrder: 2,
        isVisible: true,
        fields: [
          {
            id: 'fld_st_fname_fr',
            fieldKey: 'student_first_name_fr',
            fieldType: 'TEXT',
            labelFr: 'Prénom de l’élève (en français)',
            labelAr: 'الاسم (بالفرنسية)',
            placeholderFr: 'Ex: Mohamed',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 1,
            width: 'half',
          },
          {
            id: 'fld_st_lname_fr',
            fieldKey: 'student_last_name_fr',
            fieldType: 'TEXT',
            labelFr: 'Nom de l’élève (en français)',
            labelAr: 'اللقب (بالفرنسية)',
            placeholderFr: 'Ex: Benali',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 2,
            width: 'half',
          },
          {
            id: 'fld_st_birthdate',
            fieldKey: 'student_birth_date',
            fieldType: 'DATE',
            labelFr: 'Date de naissance',
            labelAr: 'تاريخ الميلاد',
            placeholderFr: null,
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 3,
            width: 'half',
          },
          {
            id: 'fld_st_gender',
            fieldKey: 'student_gender',
            fieldType: 'RADIO',
            labelFr: 'Sexe',
            labelAr: 'الجنس',
            placeholderFr: null,
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            optionsJson: [
              { value: 'MALE', labelFr: 'Garçon', labelAr: 'ذكر' },
              { value: 'FEMALE', labelFr: 'Fille', labelAr: 'أنثى' },
            ],
            displayOrder: 4,
            width: 'half',
          },
          {
            id: 'fld_st_current_school',
            fieldKey: 'student_current_school',
            fieldType: 'TEXT',
            labelFr: 'Établissement actuel / précédent',
            labelAr: 'المؤسسة الحالية / السابقة',
            placeholderFr: 'Ex: École Privée Les Oliviers',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: false,
            isEditableClient: true,
            isSystemProtected: false,
            displayOrder: 5,
            width: 'full',
          },
        ],
      },
      {
        id: 'sec_parent',
        key: 'parent_info',
        labelFr: 'Informations Parent / Tuteur',
        labelAr: 'معلومات الولي',
        displayOrder: 3,
        isVisible: true,
        fields: [
          {
            id: 'fld_pr_fname_fr',
            fieldKey: 'parent_first_name_fr',
            fieldType: 'TEXT',
            labelFr: 'Prénom du parent',
            labelAr: 'اسم الولي',
            placeholderFr: 'Ex: Ahmed',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 1,
            width: 'half',
          },
          {
            id: 'fld_pr_lname_fr',
            fieldKey: 'parent_last_name_fr',
            fieldType: 'TEXT',
            labelFr: 'Nom du parent',
            labelAr: 'لقب الولي',
            placeholderFr: 'Ex: Benali',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 2,
            width: 'half',
          },
          {
            id: 'fld_pr_phone',
            fieldKey: 'parent_phone',
            fieldType: 'PHONE',
            labelFr: 'Numéro de téléphone principal',
            labelAr: 'رقم الهاتف الرئيسي',
            placeholderFr: '0550 12 34 56',
            placeholderAr: null,
            helpTextFr: 'Sert d’identifiant pour le suivi de dossier en ligne.',
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 3,
            width: 'half',
          },
          {
            id: 'fld_pr_email',
            fieldKey: 'parent_email',
            fieldType: 'EMAIL',
            labelFr: 'Adresse e-mail',
            labelAr: 'البريد الإلكتروني',
            placeholderFr: 'exemple@gmail.com',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: false,
            isEditableClient: true,
            isSystemProtected: false,
            displayOrder: 4,
            width: 'half',
          },
          {
            id: 'fld_pr_address',
            fieldKey: 'parent_address',
            fieldType: 'TEXT',
            labelFr: 'Adresse de résidence',
            labelAr: 'عنوان الإقامة',
            placeholderFr: 'Ex: 14 Rue Didouche Mourad, Alger',
            placeholderAr: null,
            helpTextFr: null,
            helpTextAr: null,
            isVisible: true,
            isRequired: true,
            isEditableClient: true,
            isSystemProtected: true,
            displayOrder: 5,
            width: 'full',
          },
        ],
      },
    ],
  };

  return NextResponse.json({ success: true, data: formDefinition });
}
